
CONSUMER_API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
CONSUMER_API_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
ACCESS_TOKEN_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'



pg_host = 'mypg'
pg_username = 'postgres'
pg_port = '5432'
pg_db = 'postgres'
pg_password = '1234'
slack_token = 'XXXXXXXXXX'